"""empty message

Revision ID: 397a6c6d316d
Revises: e381986447d3
Create Date: 2023-06-10 20:38:47.825823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397a6c6d316d'
down_revision = 'e381986447d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ames', sa.Column('motdepasse', sa.String(), nullable=True))
    op.add_column('ames', sa.Column('fanavaozana', sa.Boolean(), nullable=True))
    op.add_column('ames', sa.Column('confirmation', sa.Boolean(), nullable=True))
    op.add_column('ames', sa.Column('mariage', sa.Boolean(), nullable=True))
    op.add_column('ames', sa.Column('mort', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ames', 'mort')
    op.drop_column('ames', 'mariage')
    op.drop_column('ames', 'confirmation')
    op.drop_column('ames', 'fanavaozana')
    op.drop_column('ames', 'motdepasse')
    # ### end Alembic commands ###
