"""empty message

Revision ID: 4c465483bf6c
Revises: a840e949692d
Create Date: 2023-06-10 20:24:34.233308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c465483bf6c'
down_revision = 'a840e949692d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ames', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ames', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
