"""empty message

Revision ID: 4c5a038677da
Revises: aca188142924
Create Date: 2023-06-10 20:30:41.257695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5a038677da'
down_revision = 'aca188142924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ames', sa.Column('motdepasse', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ames', 'motdepasse')
    # ### end Alembic commands ###
