"""empty message

Revision ID: a840e949692d
Revises: 16688df7e0c1
Create Date: 2023-06-10 20:20:41.105740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a840e949692d'
down_revision = '16688df7e0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ames', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_column('ames', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ames', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ames', 'password_hash')
    # ### end Alembic commands ###
