"""empty message

Revision ID: ce0c8ab4d716
Revises: 4b6b162fcd89
Create Date: 2022-12-18 12:11:23.568950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0c8ab4d716'
down_revision = '4b6b162fcd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ames', sa.Column('communion', sa.Boolean(), nullable=True))
    op.add_column('ames', sa.Column('fanavaozana', sa.Boolean(), nullable=True))
    op.add_column('ames', sa.Column('confirmation', sa.Boolean(), nullable=True))
    op.add_column('ames', sa.Column('mariage', sa.Boolean(), nullable=True))
    op.add_column('ames', sa.Column('mort', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ames', 'mort')
    op.drop_column('ames', 'mariage')
    op.drop_column('ames', 'confirmation')
    op.drop_column('ames', 'fanavaozana')
    op.drop_column('ames', 'communion')
    # ### end Alembic commands ###
