"""empty message

Revision ID: e381986447d3
Revises: 4c5a038677da
Create Date: 2023-06-10 20:33:44.978969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e381986447d3'
down_revision = '4c5a038677da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ames', sa.Column('communion', sa.Boolean(), nullable=True))
    op.drop_column('ames', 'motdepasse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ames', sa.Column('motdepasse', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ames', 'communion')
    # ### end Alembic commands ###
